apiVersion: actions.msft.isd.coe.io/v1alpha1
kind: Database
metadata:
  name: database-rbc1
spec:
  # Add fields here
  name: MyDatabase1
  server: 52.167.42.243
  port: 1433
  collationName: SQL_Latin1_General_CP1_CI_AS
  credentials:
    name: credentials
    passwordKey: password
    usernameKey: username
