apiVersion: actions.msft.isd.coe.io/v1alpha1
kind: Database
metadata:
  name: database-rbc
spec:
  # Add fields here
  name: MyDatabase2
  server: 20.62.110.48
  port: 1433
  credentials:
    name: credentials
    passwordKey: password
    usernameKey: username
